routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\RegistrarIngreso;
use App\Http\Livewire\RegistrarTercero;
use App\Http\Livewire\RegisterUser;
use App\Http\Livewire\RegistrarFactura;
use App\Http\Livewire\RegistrarEmpleados;
use App\Http\Livewire\FormCitas;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your aRegistrarFacturapplication. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
// Route::middleware(['auth:sanctum', 'verified'])->get('/register-user', function () {
//     return view('livewire.register-user');
// })->name('register-user');
Route::middleware(['auth:sanctum', 'verified'])->get('/register-role', function () {
    return view('livewire.register-role');
})->name('register-role');
// Route::middleware(['auth:sanctum', 'verified'])->get('/registrar-tercero', function () {
//     return view('livewire.registrar-tercero');
// })->name('registrar-tercero');

Route::middleware(['auth:sanctum', 'verified'])->get('/register-user', RegisterUser::class)->name('register-user');
Route::middleware(['auth:sanctum', 'verified'])->get('/agendar-citas', FormCitas::class)->name('agendar-citas');
Route::middleware(['auth:sanctum', 'verified'])->get('/registrar-ingreso', RegistrarIngreso::class)->name('registrar-ingreso');
Route::middleware(['auth:sanctum', 'verified'])->get('/registrar-tercero', RegistrarTercero::class)->name('registrar-tercero');
Route::middleware(['auth:sanctum', 'verified'])->get('/registrar-factura', RegistrarFactura::class)->name('registrar-factura');
Route::middleware(['auth:sanctum', 'verified'])->get('/registrar-empleado', RegistrarEmpleados::class)->name('registrar-empleado');

app/Http/Livewire/FormCitas.php
<?php

namespace App\Http\Livewire;

use App\Models\Terceros;
use Livewire\Component;
use App\Models\AgendarCitas;

class FormCitas extends Component
{

    public $paciente, $doctor, $datetimes, $observacion;

    public function create()
    {
        $messages = [
            'paciente.required' => 'El campo paciente es obligatorio',
            'medico.required' => 'El campo medico es obligatorio',
            'datetimes.required' => 'El campo fecha es obligatorio',
            'observacion.required' => 'El campo observacion es obligatorio'

        ];
        $this->validate([
            'paciente' => 'required',
            'doctor' => 'integer',
            'datetimes' => 'required',
            'observacion' => 'required'
        ], $messages);

        AgendarCitas::create([
            'id_tercero_paciente' => $this->paciente,
            'id_tercero_medico' => $this->doctor,
            'fecha_consulta' => $this->datetimes,
            'observacion' => $this->observacion
        ]);

        $this->reset(['paciente', 'doctor', 'datetimes', 'observacion']);
    }

    public function render()
    {
        $medicos = terceros::get()->where('typeTercero', '=', 'Médico');
        $clientes = terceros::get()->where('typeTercero', '=', 'Cliente');
        $citas = AgendarCitas::all();

        return view('livewire.form-citas', compact('medicos', 'clientes', 'citas'));
    }
}

app/Http/Livewire/FormEmpleados.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Empleados;


class FormEmpleados extends Component
{
    public $viewButton = 'store';
    public $cEmpleado, $name, $cargo;
    public function render()
    {
        return view('livewire.form-empleados' , [
            'empleados' => Empleados::paginate(5)
        ]);
    }
    public function store(){
        $messages = [
            'name.required' => 'El campo nombre es obligatorio ',
            'cargo.required' => 'El campo cargo es obligatorio',
            'cEmpleado.required' => 'El campo código es obligatorio',
        ];
        $this->validate([
            'name' => 'required',
            'cEmpleado' => 'required',
            'cargo' => 'required',
        ], $messages);

        Empleados::create([
            'name' => $this->name,
            'cargo' => $this->cargo,
            'cEmpleado' => $this->cEmpleado,

        ]);
        $this->reset(['name', 'cEmpleado', 'cargo']);

        $this->alert('success', 'Empleado creado correctamente!', [
            'position' =>  'top-end', 
            'timer' =>  '4000', 
            'toast' =>  true, 
            'text' =>  '', 
            'confirmButtonText' =>  'Ok', 
            'cancelButtonText' =>  'Cancel', 
            'showCancelButton' =>  false, 
            'showConfirmButton' =>  false, 
        ]);
    }
}

app/Http/Livewire/FormFacturas.php
<?php

namespace App\Http\Livewire;

use App\Models\Facturas;
use Livewire\Component;
use Livewire\WithPagination;

class FormFacturas extends Component
{
    
    public $consecutivo = 00001;
    public $nFactura = '00001';
    public $centroCostosName = 'Rubro';
    public $plazoName = 'X meses';

    public $view = 'store';
    public $viewButton = 'store';
    public $buscar, $fechaIngreso, $prefijo, $plazo, $centroCostos,
        $idVendedor, $productoServicio, $descuento, $nameTercero, $adress, $city, $phone, $rLegal, $nameTerceroVendedor;

    public function doSomething(){
        $this->alert('success', 'calculando Iva!', [
            'position' =>  'top-end', 
            'timer' =>  '4000', 
            'toast' =>  true, 
            'text' =>  '', 
            'confirmButtonText' =>  'Ok', 
            'cancelButtonText' =>  'Cancel', 
            'showCancelButton' =>  false, 
            'showConfirmButton' =>  false, 
        ]);
    }
    public function render()
    {
        return view('livewire.form-facturas', [
            'facturas' => Facturas::paginate(3),
            
        ]);
    }
    
    public function changeView($data){        
        $this->view = $data;

    }
}

app/Http/Livewire/FormTerceros.php
<?php

namespace App\Http\Livewire;
use App\Models\Terceros;
use Livewire\Component;
use Livewire\WithPagination;

class FormTerceros extends Component
{
    public $locations = 
    ['Abejorral - Antioquia',
    'Abriaquí - Antioquia',
    'Alejandría - Antioquia',
    'Amagá - Antioquia',
    'Amalfi - Antioquia',
    'Andes - Antioquia',
    'Angelópolis - Antioquia',
    'Angostura - Antioquia',
    'Anorí - Antioquia',
    'Anzá - Antioquia',
    'Apartadó - Antioquia',
    'Arboletes - Antioquia',
    'Argelia - Antioquia',
    'Armenia - Antioquia',
    'Barbosa - Antioquia',
    'Bello - Antioquia',
    'Belmira - Antioquia',
    'Betania - Antioquia',
    'Betulia - Antioquia',
    'Briceño - Antioquia',
    'Buriticá - Antioquia',
    'Cáceres - Antioquia',
    'Caicedo - Antioquia',
    'Caldas - Antioquia',
    'Campamento - Antioquia',
    'Cañasgordas - Antioquia',
    'Caracolí - Antioquia',
    'Caramanta - Antioquia',
    'Carepa - Antioquia',
    'Carolina - Antioquia',
    'Caucasia - Antioquia',
    'Chigorodó - Antioquia',
    'Cisneros - Antioquia',
    'Ciudad Bolívar - Antioquia',
    'Cocorná - Antioquia',
    'Concepción - Antioquia',
    'Concordia - Antioquia',
    'Copacabana - Antioquia',
    'Dabeiba - Antioquia',
    'Donmatías - Antioquia',
    'Ebéjico - Antioquia',
    'El Bagre - Antioquia',
    'El Carmen De Viboral - Antioquia',
    'El Santuario - Antioquia',
    'Entrerríos - Antioquia',
    'Envigado - Antioquia',
    'Fredonia - Antioquia',
    'Frontino - Antioquia',
    'Giraldo - Antioquia',
    'Girardota - Antioquia',
    'Gómez Plata - Antioquia',
    'Granada - Antioquia',
    'Guadalupe - Antioquia',
    'Guarne - Antioquia',
    'Guatapé - Antioquia',
    'Heliconia - Antioquia',
    'Hispania - Antioquia',
    'Itagüí - Antioquia',
    'Ituango - Antioquia',
    'Jardín - Antioquia',
    'Jericó - Antioquia',
    'La Ceja - Antioquia',
    'La Estrella - Antioquia',
    'La Pintada - Antioquia',
    'La Unión - Antioquia',
    'Liborina - Antioquia',
    'Maceo - Antioquia',
    'Marinilla - Antioquia',
    'Medellín - Antioquia',
    'Montebello - Antioquia',
    'Murindó - Antioquia',
    'Mutatá - Antioquia',
    'Nariño - Antioquia',
    'Nechí - Antioquia',
    'Necoclí - Antioquia',
    'Olaya - Antioquia',
    'Peñol - Antioquia',
    'Peque - Antioquia',
    'Pueblorrico - Antioquia',
    'Puerto Berrío - Antioquia',
    'Puerto Nare - Antioquia',
    'Puerto Triunfo - Antioquia',
    'Remedios - Antioquia',
    'Retiro - Antioquia',
    'Rionegro - Antioquia',
    'Sabanalarga - Antioquia',
    'Sabaneta - Antioquia',
    'Salgar - Antioquia',
    'San Andrés De Cuerquía - Antioquia',
    'San Carlos - Antioquia',
    'San Francisco - Antioquia',
    'San Jerónimo - Antioquia',
    'San José De La Montaña - Antioquia',
    'San Juan De Urabá - Antioquia',
    'San Luis - Antioquia',
    'San Pedro De Los Milagros - Antioquia',
    'San Pedro De Urabá - Antioquia',
    'San Rafael - Antioquia',
    'San Roque - Antioquia',
    'San Vicente Ferrer - Antioquia',
    'Santa Bárbara - Antioquia',
    'Santa Fé De Antioquia - Antioquia',
    'Santa Rosa De Osos - Antioquia',
    'Santo Domingo - Antioquia',
    'Segovia - Antioquia',
    'Sonsón - Antioquia',
    'Sopetrán - Antioquia',
    'Támesis - Antioquia',
    'Tarazá - Antioquia',
    'Tarso - Antioquia',
    'Titiribí - Antioquia',
    'Toledo - Antioquia',
    'Turbo - Antioquia',
    'Uramita - Antioquia',
    'Urrao - Antioquia',
    'Valdivia - Antioquia',
    'Valparaíso - Antioquia',
    'Vegachí - Antioquia',
    'Venecia - Antioquia',
    'Vigía Del Fuerte - Antioquia',
    'Yalí - Antioquia',
    'Yarumal - Antioquia',
    'Yolombó - Antioquia',
    'Yondó - Antioquia',
    'Zaragoza - Antioquia',
    'El Encanto - Amazonas',
    'La Chorrera - Amazonas',
    'La Pedrera - Amazonas',
    'La Victoria - Amazonas',
    'Leticia - Amazonas',
    'Mirití - Paraná - Amazonas',
    'Puerto Alegría - Amazonas',
    'Puerto Arica - Amazonas',
    'Puerto Nariño - Amazonas',
    'Puerto Santander - Amazonas',
    'Tarapacá - Amazonas',
    'Arauca - Arauca',
    'Arauquita - Arauca',
    'Cravo Norte - Arauca',
    'Fortul - Arauca',
    'Puerto Rondón - Arauca',
    'Saravena - Arauca',
    'Tame - Arauca',
    'Baranoa - Atlántico',
    'Barranquilla - Atlántico',
    'Campo De La Cruz - Atlántico',
    'Candelaria - Atlántico',
    'Galapa - Atlántico',
    'Juan De Acosta - Atlántico',
    'Luruaco - Atlántico',
    'Malambo - Atlántico',
    'Manatí - Atlántico',
    'Palmar De Varela - Atlántico',
    'Piojó - Atlántico',
    'Polonuevo - Atlántico',
    'Ponedera - Atlántico',
    'Puerto Colombia - Atlántico',
    'Repelón - Atlántico',
    'Sabanagrande - Atlántico',
    'Sabanalarga - Atlántico',
    'Santa Lucía - Atlántico',
    'Santo Tomás - Atlántico',
    'Soledad - Atlántico',
    'Suan - Atlántico',
    'Tubará - Atlántico',
    'Usiacurí - Atlántico',
    'Bogotá, D.C. - Bogotá, D. C.',
    'Achí - Bolívar',
    'Altos Del Rosario - Bolívar',
    'Arenal - Bolívar',
    'Arjona - Bolívar',
    'Arroyohondo - Bolívar',
    'Barranco De Loba - Bolívar',
    'Calamar - Bolívar',
    'Cantagallo - Bolívar',
    'Cartagena De Indias - Bolívar',
    'Cicuco - Bolívar',
    'Clemencia - Bolívar',
    'Córdoba - Bolívar',
    'El Carmen De Bolívar - Bolívar',
    'El Guamo - Bolívar',
    'El Peñón - Bolívar',
    'Hatillo De Loba - Bolívar',
    'Magangué - Bolívar',
    'Mahates - Bolívar',
    'Margarita - Bolívar',
    'María La Baja - Bolívar',
    'Mompós - Bolívar',
    'Montecristo - Bolívar',
    'Morales - Bolívar',
    'Norosí - Bolívar',
    'Pinillos - Bolívar',
    'Regidor - Bolívar',
    'Río Viejo - Bolívar',
    'San Cristóbal - Bolívar',
    'San Estanislao - Bolívar',
    'San Fernando - Bolívar',
    'San Jacinto - Bolívar',
    'San Jacinto Del Cauca - Bolívar',
    'San Juan Nepomuceno - Bolívar',
    'San Martín De Loba - Bolívar',
    'San Pablo - Bolívar',
    'Santa Catalina - Bolívar',
    'Santa Rosa - Bolívar',
    'Santa Rosa Del Sur - Bolívar',
    'Simití - Bolívar',
    'Soplaviento - Bolívar',
    'Talaigua Nuevo - Bolívar',
    'Tiquisio - Bolívar',
    'Turbaco - Bolívar',
    'Turbaná - Bolívar',
    'Villanueva - Bolívar',
    'Zambrano - Bolívar',
    'Almeida - Boyacá',
    'Aquitania - Boyacá',
    'Arcabuco - Boyacá',
    'Belén - Boyacá',
    'Berbeo - Boyacá',
    'Betéitiva - Boyacá',
    'Boavita - Boyacá',
    'Boyacá - Boyacá',
    'Briceño - Boyacá',
    'Buenavista - Boyacá',
    'Busbanzá - Boyacá',
    'Caldas - Boyacá',
    'Campohermoso - Boyacá',
    'Cerinza - Boyacá',
    'Chinavita - Boyacá',
    'Chiquinquirá - Boyacá',
    'Chíquiza - Boyacá',
    'Chiscas - Boyacá',
    'Chita - Boyacá',
    'Chitaraque - Boyacá',
    'Chivatá - Boyacá',
    'Chivor - Boyacá',
    'Ciénega - Boyacá',
    'Cómbita - Boyacá',
    'Coper - Boyacá',
    'Corrales - Boyacá',
    'Covarachía - Boyacá',
    'Cubará - Boyacá',
    'Cucaita - Boyacá',
    'Cuítiva - Boyacá',
    'Duitama - Boyacá',
    'El Cocuy - Boyacá',
    'El Espino - Boyacá',
    'Firavitoba - Boyacá',
    'Floresta - Boyacá',
    'Gachantivá - Boyacá',
    'Gámeza - Boyacá',
    'Garagoa - Boyacá',
    'Guacamayas - Boyacá',
    'Guateque - Boyacá',
    'Guayatá - Boyacá',
    'Güicán De La Sierra - Boyacá',
    'Iza - Boyacá',
    'Jenesano - Boyacá',
    'Jericó - Boyacá',
    'La Capilla - Boyacá',
    'La Uvita - Boyacá',
    'La Victoria - Boyacá',
    'Labranzagrande - Boyacá',
    'Macanal - Boyacá',
    'Maripí - Boyacá',
    'Miraflores - Boyacá',
    'Mongua - Boyacá',
    'Monguí - Boyacá',
    'Moniquirá - Boyacá',
    'Motavita - Boyacá',
    'Muzo - Boyacá',
    'Nobsa - Boyacá',
    'Nuevo Colón - Boyacá',
    'Oicatá - Boyacá',
    'Otanche - Boyacá',
    'Pachavita - Boyacá',
    'Páez - Boyacá',
    'Paipa - Boyacá',
    'Pajarito - Boyacá',
    'Panqueba - Boyacá',
    'Pauna - Boyacá',
    'Paya - Boyacá',
    'Paz De Río - Boyacá',
    'Pesca - Boyacá',
    'Pisba - Boyacá',
    'Puerto Boyacá - Boyacá',
    'Quípama - Boyacá',
    'Ramiriquí - Boyacá',
    'Ráquira - Boyacá',
    'Rondón - Boyacá',
    'Saboyá - Boyacá',
    'Sáchica - Boyacá',
    'Samacá - Boyacá',
    'San Eduardo - Boyacá',
    'San José De Pare - Boyacá',
    'San Luis De Gaceno - Boyacá',
    'San Mateo - Boyacá',
    'San Miguel De Sema - Boyacá',
    'San Pablo De Borbur - Boyacá',
    'Santa María - Boyacá',
    'Santa Rosa De Viterbo - Boyacá',
    'Santa Sofía - Boyacá',
    'Santana - Boyacá',
    'Sativanorte - Boyacá',
    'Sativasur - Boyacá',
    'Siachoque - Boyacá',
    'Soatá - Boyacá',
    'Socha - Boyacá',
    'Socotá - Boyacá',
    'Sogamoso - Boyacá',
    'Somondoco - Boyacá',
    'Sora - Boyacá',
    'Soracá - Boyacá',
    'Sotaquirá - Boyacá',
    'Susacón - Boyacá',
    'Sutamarchán - Boyacá',
    'Sutatenza - Boyacá',
    'Tasco - Boyacá',
    'Tenza - Boyacá',
    'Tibaná - Boyacá',
    'Tibasosa - Boyacá',
    'Tinjacá - Boyacá',
    'Tipacoque - Boyacá',
    'Toca - Boyacá',
    'Togüí - Boyacá',
    'Tópaga - Boyacá',
    'Tota - Boyacá',
    'Tunja - Boyacá',
    'Tununguá - Boyacá',
    'Turmequé - Boyacá',
    'Tuta - Boyacá',
    'Tutazá - Boyacá',
    'Úmbita - Boyacá',
    'Ventaquemada - Boyacá',
    'Villa De Leyva - Boyacá',
    'Viracachá - Boyacá',
    'Zetaquira - Boyacá',
    'Aguadas - Caldas',
    'Anserma - Caldas',
    'Aranzazu - Caldas',
    'Belalcázar - Caldas',
    'Chinchiná - Caldas',
    'Filadelfia - Caldas',
    'La Dorada - Caldas',
    'La Merced - Caldas',
    'Manizales - Caldas',
    'Manzanares - Caldas',
    'Marmato - Caldas',
    'Marquetalia - Caldas',
    'Marulanda - Caldas',
    'Neira - Caldas',
    'Norcasia - Caldas',
    'Pácora - Caldas',
    'Palestina - Caldas',
    'Pensilvania - Caldas',
    'Riosucio - Caldas',
    'Risaralda - Caldas',
    'Salamina - Caldas',
    'Samaná - Caldas',
    'San José - Caldas',

app/Http/Livewire/RegisterRole.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Role;
class RegisterRole extends Component
{
    public $rolename = "medco" ;
    public $description;
    public function render()
    {
        return view('livewire.register-role',[
            'users' => Role::paginate(2)
        ]);
    }
    public function store()
    {
        $messages = [
            'name.required' => 'El campo nombre es obligatorio ',
            'description.required' => 'El descripción  es obligatorio',
            
        ];
        $this->validate([
            'name' => 'required',
            'email' => 'required|unique:users|email',
        ], $messages);
        
        // User::create([
        //     'name' => $this->name,
        //     'email' => $this->email,
        //     'role' => $this->role,
        //     'password' => Hash::make($this->password),
        // ]);
        // $this->reset(['name', 'email', 'role', 'password']);

    }
}

app/Http/Livewire/RegisterUser.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;

class RegisterUser extends Component
{   
    public function render()
    {
        return view('livewire.register-user',[
            'users' => User::paginate()
        ]);
    }
    
    

    
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/livewire/register-role.blade.php
<x-app-layout>
    <div class="bg-white grid grid-cols-2 overflow-hidden shadow-xl sm:rounded-lg">
        <div class="flex flex-col divide-x divide-gray-200">
            <div class=" overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Nombre
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Role
                                    </th>

                                    <th scope="col" class="relative px-6 py-3">
                                        <span class="sr-only">Edit</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">

                                {{-- @foreach ($roles as $role) --}}


                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="flex items-center">
                                                {{-- <div class="flex-shrink-0 h-10 w-10">
                                                    <img class="h-10 w-10 rounded-full"
                                                        src="{{ $user->profile_photo_url }}"
                                                        alt="{{ $user->name }}">
                                                </div> --}}
                                                <div class="ml-4">
                                                    <div class="text-sm font-medium text-gray-900">
                                                        {{-- {{ $user->name }} --}}
                                                    </div>
                                                    <div class="text-sm text-gray-500">
                                                        {{-- {{ $user->email }} --}}
                                                    </div>
                                                </div>
                                            </div>
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{-- {{ $user->role }} --}}
                                        </td>
                                        {{-- <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <a wire:click="update({{ $user->id }})" href="#"
                                                class="text-indigo-600 hover:text-indigo-900"><i
                                                    class="fas fa-edit"></i></a>
                                            <a wire:click="destroy({{ $user->id }})" href="#"
                                                class="text-red-600 hover:text-red-900"><i
                                                    class="fas fa-trash"></i></a>
                                        </td> --}}
                                    </tr>
                                {{-- @endforeach --}}


                                <!-- More rows... -->
                            </tbody>
                        </table>
                            {{-- {{ $users->links() }} --}}
                        
                    </div>
                </div>
            </div>
        </div>
        <form class="px-5 pt-5" wire:submit.prevent="store">
            <div class="overflow-hidden">
                <div class="px-4 py-5 bg-white sm:p-6">
                    <div class="grid grid-cols-12">
                        <div class="col-span-12 sm:col-span-12 mb-5">
                            <label for="first_name" class="block text-sm font-medium text-gray-700">Nombre
                                del role</label>
                            <input style="text-transform:capitalize" wire:model.lazy="rolename" type="text"
                                name="first_name" id="first_name" autocomplete="off"
                                class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('name')
                                <span class="text-sm text-red-600">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-span-12 sm:col-span-3 mb-5">
                            <label for="street_address"
                                class="block text-sm font-medium text-gray-700">Descripción</label>
                            <textarea wire:model.lazy="description" type="password" name="street_address"
                                id="street_address" autocomplete="off"
                                class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
                            @error('description')
                                <span class="text-sm text-red-600">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="px-4 py-3 text-right sm:px-6">
                    <button type="submit"
                        class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <span wire:loading.attr="hidden">{{ __('Save') }} </span>
                        <span wire:loading wire:target="store">Procesando...</span>
                    </button>


                </div>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/livewire/register-user.blade.php
    <div class="grid w-full">     
    <livewire:form />
    </div>

resources/views/livewire/registrar-citas.blade.php
<div class="grid w-full">      
    
    <livewire:form-citas />

</div>

resources/views/livewire/registrar-empleados.blade.php
<div class="grid w-full">
    <livewire:form-empleados />
</div>

resources/views/livewire/registrar-factura.blade.php
<div class="grid w-full">      
    
    <livewire:form-facturas />

</div>

resources/views/livewire/registrar-ingreso.blade.php
<div>
    {{-- Knowing others is intelligence; knowing yourself is true wisdom. --}}
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque beatae harum consequuntur incidunt dignissimos esse aspernatur ipsum veritatis deserunt? Alias expedita a saepe veniam quo, optio repellat voluptatem corrupti totam?</p>
</div>

resources/views/livewire/registrar-tercero.blade.php
<div class="grid w-full">      
    
    <livewire:form-terceros />

</div>

resources/views/livewire/users-table.blade.php
<div>
    {{-- Success is as dangerous as failure. --}}
</div>